# Use the official NGINX image as the base image
FROM nginx:alpine

# Copy frontend files into the NGINX html directory
COPY ./frontend /usr/share/nginx/html

# Expose the default port NGINX runs on
EXPOSE 80