version: '3.9'
services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
    networks:
      - stock-net

networks:
  stock-net: