version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://db:27017/trading_db
      - FLASK_APP=stock_monitor.py
    networks:
      - stock_network

  frontend:
    build:
      context: .  # Set the build context to the root of the project directory
      dockerfile: frontend/Dockerfile  # This points to the Dockerfile inside the frontend folder
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/share/nginx/html  # Ensure the frontend content is correctly mounted
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf  # Mount the custom nginx.conf from the frontend folder
    networks:
      - stock_network

  db:
    image: mongo:latest
    volumes:
      - db_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=trading_db
    networks:
      - stock_network

volumes:
  db_data:

networks:
  stock_network:
    driver: bridge